Downloads/TCCclothing-main/devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Downloads/TCCclothing-main/projects/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.menCatalog, name="profiles"),
    path('projec/<id>/', views.project, name="project"),
    path('men/', views.menCatalog, name="men"),
    path('men/<type>/', views.menCatalogSpecific, name="men-specific"),
    path('women/<type>/', views.womenCatalogSpecific, name="women-specific"),
    path('kids/<type>/', views.kidsCatalogSpecific, name="kids-specific"),
    path('women/', views.womenCatalog, name="women"),
    path('sale/<gender>/', views.saleCatalog, name="sale"),
    path('kids/', views.kidsCatalog, name="kids"),
    path('register/', views.SignUp.as_view(), name="register"),
    path('login/', views.login_view, name='login'),
    path('cart/', views.cartView, name="cart"),
    path('logout/', views.logout_view, name="logout"),
    path('account/', views.userAccount, name="account"),
    path('account-details/', views.accountDetails, name="account-details"),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('edit-account/', views.editAccount, name="edit-account"),
    path('password_change_form/', auth_views.PasswordChangeView.as_view(), name="password_change_form"),
     path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
     path('addToCart/<item>/', views.addToCartView, name='addToCartView'),
     path('purchaseSuccess/' , views.purchaseView, name='purchaseSuccess'),
     path('updateCartItem/<pk>/', views.AddCartItem, name="updateCartItem"),
     path('deleteCartItem/<pk>/', views.DeleteCartItem, name="deleteCartItem")
]

Downloads/TCCclothing-main/projects/models.py
from xml.dom.pulldom import default_bufsize
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver



class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)

    def __str__(self):
        return self.name


class Details(models.Model):
    detail_name = models.CharField(unique=True, max_length=50, blank=True, null=True)
    gender = models.CharField(max_length=6, blank=True, null=True)
    purpose = models.CharField(max_length=50, blank=True, null=True)
    description = models.CharField(max_length=200, blank=True, null=True)
    def __str__(self):
        return self.detail_name

class Color(models.Model):
    color_name = models.CharField(unique=True, max_length=50, blank=True, null=True)
    color_id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    def __str__(self):
        return self.color_name

class Sale(models.Model):
    sale_name = models.CharField(unique=True, max_length=50, blank=True, null=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    def __str__(self):
        return self.sale_name
class Fit(models.Model):
    fit_name = models.CharField(unique=True, max_length=50, blank=True, null=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    def __str__(self):
        return self.fit_name
class Material(models.Model):
    material_name = models.CharField(unique=True, max_length=50, blank=True, null=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    def __str__(self):
        return self.material_name

class Item(models.Model):
    item_name = models.CharField(max_length=50, blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    on_sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    picture = models.ImageField(null=True, blank=True, default="default.jpg")
    details = models.CharField(max_length=255, blank=True, null=True)
    gender = models.CharField(max_length=255, blank=True, null=True)
    fit = models.ForeignKey(Fit, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    type = models.CharField(max_length=50, blank=True, null=True)
    def __str__(self):
        return self.item_name

class Review(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default='')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    


class CartItem(models.Model):
    itemInCart = models.ForeignKey(Item, on_delete=models.CASCADE, null=True)
    cartOwner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default='')
    size = models.CharField(max_length=2, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    added = models.DateTimeField(auto_now_add=True)
    purchased = models.CharField(max_length=5, blank=True, null=True, default="False")
    def __str__(self):
        return str(self.cartOwner)+" "+str(self.itemInCart)

class Purchase(models.Model):
    purchasedItemIds = models.CharField(max_length=500, null=True, blank=True)
    purchaseOwner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default='')
    size = models.CharField(max_length=2, blank=True, null=True)
    totalPrice = models.CharField(max_length=400, null=True, blank=True)
    purchaseDate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.purchaseOwner)+"; "+"$"+self.totalPrice+"; "+str(self.purchaseDate)
# @reciever(post_save, sender=User)
# def orderMade(sender, instance, created, **kwargs):
#     print("order made")
#     print('instance:', instance)
#     print('created:', created)

# post_save.connect(orderMade, sender=User)

Downloads/TCCclothing-main/projects/forms.py
from cProfile import Profile
from .models import Review, CartItem, Purchase
from  django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView, CreateView
from django.views import generic


class CustomUserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','phone_number','password1','password2','gender']

class CustomUserUpdateForm(UpdateView):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','phone_number']

# create update form for users
class ProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','phone_number']

class CommentForm(ModelForm):
    class Meta:
        model = Review
        fields = ['body']

class CartAddForm(ModelForm):
    class Meta:
        model = CartItem
        fields = '__all__'

class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'

Downloads/TCCclothing-main/projects/views.py
from cProfile import Profile
from django.shortcuts import render, redirect
from .forms import CartAddForm, ProfileForm
import locale
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from projects.utils import searchItems, specific, sale
from .forms import CustomUserCreateForm, CommentForm, PurchaseForm
from django.views import generic
from django.contrib.auth.forms import UserChangeForm
from .models import Details, Review, Tag, Item, Color, Material, Fit, CartItem, Purchase
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models import F
from projects.filters import ColorFilter
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.models import User

def profiles(request):
    return render(request, 'profiles.html')

class SignUp(CreateView):
    success_url = reverse_lazy("login")
    template_name = 'registration/registration.html'
    form_class = CustomUserCreateForm
    def get_absolute_url(self):
        return ('men')


@login_required(login_url='login')
def cartView(request):
    total = 0
    cartSize = 0
    cartIds = ""
    cartItems = CartItem.objects.filter(purchased="False")
    for i in cartItems:
        types = i.quantity
        if i.cartOwner == request.user:
            if i.itemInCart.on_sale.sale_name == "On Sale":
                total += (i.itemInCart.price * .6)*i.quantity
                cartSize += 1
                cartIds += (str(i.id)+" ")
            else:
                total += (i.itemInCart.price)*i.quantity
                cartSize += 1
                cartIds += (str(i.id)+" ")
    totalf = "{:.2f}".format(total)
    cartIds = cartIds[:len(cartIds)-1]
    context = {'cartItems':cartItems,'total':totalf,'cartSize':cartSize,'cartIds':cartIds}
    return render(request, 'cart.html', context)


def logout_view(request):
    logout(request)
    return redirect('login')

def login_view(request):
  context = {"login_view": "active"}
  if request.method == "POST":
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
      login(request, user)
      return redirect("men")
    else:
      return HttpResponse("invalid credentials")
  return render(request, "registration/login.html", context)
    
@login_required(login_url='login')
def menCatalog(request):
    item, search_query, color, material, fit, itemAll, myFilter, details, paginator = searchItems(request)
    context = {'search_query':search_query,'item':item,'myFilter':myFilter, 'itemAll':itemAll,'color':color,'fit':fit,'material':material, "paginator":paginator }
    return render(request, 'men.html', context,)

@login_required(login_url='login')
def menCatalogSpecific(request, type):
    item, search_query, color, material, fit, itemAll, myFilter, details, paginator = specific(request, type)
    context = {'search_query':search_query,'item':item,'myFilter':myFilter, 'itemAll':itemAll,'color':color,'fit':fit,'material':material, "paginator":paginator }
    return render(request, 'men.html', context,)

@login_required(login_url='login')
def womenCatalogSpecific(request, type):
    item, search_query, color, material, fit, itemAll, myFilter, details, paginator = specific(request, type)
    item = Item.objects.filter(type=str(type)).annotate(prod=F('price')*.6)
    context = {'search_query':search_query,'item':item,'myFilter':myFilter, 'itemAll':itemAll,'color':color,'fit':fit,'material':material, "paginator":paginator }
    return render(request, 'women.html', context,)

@login_required(login_url='login')
def kidsCatalogSpecific(request, type):
    item, search_query, color, material, fit, itemAll, myFilter, details, paginator = specific(request, type)
    context = {'search_query':search_query,'item':item,'myFilter':myFilter, 'itemAll':itemAll,'color':color,'fit':fit,'material':material, "paginator":paginator }
    return render(request, 'kids.html', context,)

@login_required(login_url='login')
def saleCatalog(request, gender):
    item, search_query, color, material, fit, itemAll, myFilter, details, paginator = sale(request, gender)
    context = {'search_query':search_query,'item':item,'myFilter':myFilter, 'itemAll':itemAll,'color':color,'fit':fit,'material':material, "paginator":paginator,'gender':gender }
    return render(request, 'sale.html', context)

@login_required(login_url='login')
def kidsCatalog(request):
    item, search_query, color, material, fit, itemAll, myFilter, details, paginator = searchItems(request)
    context = {'search_query':search_query,'item':item,'myFilter':myFilter, 'itemAll':itemAll,'color':color,'fit':fit,'material':material, "paginator":paginator }
    return render(request, 'kids.html', context)

@login_required(login_url='login')
def womenCatalog(request):
    item, search_query, color, material, fit, itemAll, myFilter, details, paginator = searchItems(request)
    context = {'search_query':search_query,'item':item,'myFilter':myFilter, 'itemAll':itemAll,'color':color,'fit':fit,'material':material, "paginator":paginator }
    return render(request, 'women.html', context,)

@login_required(login_url='login')
def project(request, id):
    # show price on the single project view
    form2 = CartAddForm()
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        review = form.save()
        review.item = Item.objects.get(id=id)
        review.owner = request.user
        review.save()
    revLen = 0
    review = Review.objects.all()
    for rev in review:
        if rev.item == Item.objects.get(id=id):
            revLen += 1
    item, search_query, color, material, fit, itemAll, myFilter, details, paginator = searchItems(request)
    item = Item.objects.get(id=id)
    context = {'revLen':revLen,'form2':form2,'review':review,'search_query':search_query,'i':item,'myFilter':myFilter,'details':details, 'itemAll':itemAll,'color':color,'fit':fit,'material':material, 'object':object, 'form':form }
    return render(request, 'single-project.html', context)

@login_required(login_url='login')
def addToCartView(request, item):
    # make it so that if the item they are sdding to the cart already exists it
    # just updates the quantity
    #create an equals method
    cartitems = CartItem.objects.all()
    form = CartAddForm()
    if request.method == "POST":
        form = CartAddForm(request.POST)
        cartitem = form.save()
        cartitem.save()
        return redirect('project', item)




def AddCartItem(request, pk):
    # make buttons smaller and add an option addToCartViewsubract from the cart
    cartitem = CartItem.objects.get(id=pk)
    form = CartAddForm(instance=cartitem)
    if request.method == "POST":
        form = CartAddForm(request.POST, request.FILES,  instance=cartitem)
        if form.is_valid():
            cartitem.quantity += 1
            form.save()
            return redirect('cart')


def DeleteCartItem(request, pk):
    # make buttons smaller and add an option addToCartViewsubract from the cart
    cartitem = CartItem.objects.get(id=pk)
    form = CartAddForm(instance=cartitem)
    if request.method == "POST":
        form = CartAddForm(request.POST, request.FILES,  instance=cartitem)
        if form.is_valid():
            cartitem.quantity -= 1
            form.save()
        if cartitem.quantity == 0:
            cartitem.delete()
        return redirect('cart')

def userAccount(request):
    context = {"user":request.user}
    return render(request, 'accounts.html', context)

def accountDetails(request):
    cartitem = CartItem.objects.filter(purchased="True")
    # remove store credit and make that an order section thT SHOWS 2
    # OPTIONS AND GIVES THEM A LINK TO CLICK IF THEY 
    # WANT TO SEE ALL
    purchases = Purchase.objects.filter(purchaseOwner=request.user)
    purchaseLen = len(purchases)
    for i in range(len(purchases)):
        purchases[i].purchasedItemIds = purchases[i].purchasedItemIds.split(' ')
        purchases[i].purchasedItemIds = list(map(int, purchases[i].purchasedItemIds))
    context = {'user':request.user, 'purchases':purchases, 'purLen':purchaseLen, 'cartitem':cartitem}
    return render(request, 'registration/account-details.html', context)


def editAccount(request):
    user = request.user
    form = ProfileForm(instance=user)

    if request.method == 'POST':
        form = ProfileForm(request.POST,  instance=user)
        if form.is_valid():
            form.save()
            return redirect('men')
    context = {'form':form}
    return render(request, 'registration/updateuser.html', context)

def purchaseView(request):
    # just finish the view
    # pull all the data from the cartitem instances before delete() is called
    if request.method == "POST":
        form = PurchaseForm(request.POST)
        purchase = form.save()
        purchase.save()
        itemIds = purchase.purchasedItemIds.split(' ')
        itemIds = list(map(int, itemIds))
        for cartItemId in itemIds:
            item = CartItem.objects.get(id=cartItemId)
            item.purchased = "True"
            item.save()
        context = {'idli':itemIds}
        return render(request, 'projects/purchase.html', context)

Downloads/TCCclothing-main/projects/templates/cart.html
{% extends 'projects/main.html' %}
{% load mathfilters %}
{% block content %}
<h1 style="text-align:center">Shopping Cart</h1>
{% if cartSize == 0 %}
<h3 style="text-align: center;  margin-top: 80px; color: black;">YOUR SHOPPING CART IS EMPTY!</h3>
<p style="text-align: center; color: black; font-size: larger;">Click <a href="{% url 'men' %}" style="color: #4f97a9;">here</a> to continue shopping.</p>
{%else%}
{% for item in cartItems %}
{%if item.cartOwner == request.user and item.purchased != "True" %}
<div style="width: 60%; margin-bottom: 40px; background-color: rgb(255, 255, 255); height: 195px; margin-left: 19px; border-left: solid 3px rgb(0, 0, 0);">
    <div style="display: inline;">
        <a href="{% url 'project' item.itemInCart.id %}"><img src="{{item.itemInCart.picture.url}}" style="width: 180px; height: 195px;"></a>
    </div>
    <div style="display: inline; vertical-align: top; margin-left: 1%;">
        <table style="display: inline;">
            <tr>
                <td>
                    <p style="color: black;">{{item.itemInCart.item_name}}</p>
                    {% if item.itemInCart.on_sale.sale_name == "On Sale" %}
                    <p style="color: black;">${{item.itemInCart.price|mul:0.6|stringformat:".2f"}}</p>
                    {% else %}
                    <p style="color: black;">${{item.itemInCart.price}}</p>
                    {%endif%}
                    <br>
                    <p style="color: black; font-size: small;">Size: {{item.size}}</p>
                    <p style="color: black; font-size: small;">Color: {{item.itemInCart.color.color_name}}</p>
                </td>
                <td>
                    <p style="margin-top: 3px;"></p>
                    <br>
                    <br>
                    <br>
                    <p style="color: black; font-size: small; display: inline;">Quantity: </p>
                    <form method="POST" action="{% url 'deleteCartItem' item.id %}" style="display: inline;">
                        {%csrf_token%}
                        <input type="text" name="size" value="{{item.size}}" required="" id="id_size" style="display: none;">
                        <input type="text" name="itemInCart" value="{{item.itemInCart.id}}" min="0" required="" id="id_itemInCart" style="display: none;">
                        <input type="text" name="cartOwner" value="{{item.cartOwner.id}}" required="" id="id_cartOwner" style="display: none;">
                        <input type="text" name="quantity" value="{{item.quantity}}" required="" id="id_quantity" style="display: none;">
                        <input class="btn btn--sub" type="submit" value="-" >
                    </form>
                    <form method="POST" action="{% url 'updateCartItem' item.id %}" style="display: inline;">
                        {%csrf_token%}
                        <input type="text" name="size" value="{{item.size}}" required="" id="id_size" style="display: none;">
                        <input type="text" name="itemInCart" value="{{item.itemInCart.id}}" min="0" required="" id="id_itemInCart" style="display: none;">
                        <input type="text" name="cartOwner" value="{{item.cartOwner.id}}" required="" id="id_cartOwner" style="display: none;">
                        <input type="text" name="quantity" value="{{item.quantity}}" required="" id="id_quantity" style="width: 14%; display: inline; height: 20px;">
                        <input class="btn btn--sub" type="submit" value="+">
                    </form>
                    {% if item.itemInCart.on_sale.sale_name == "On Sale" %}
                    <p style="color: black; font-size: small;">Total: ${{item.itemInCart.price|mul:0.6|stringformat:".2f"}}</p>
                    {%else%}
                    <p style="color: black;  font-size: small;">Total: ${{item.itemInCart.price}}</p>
                    {%endif%}
                </td>
            </tr>
        </table>
    </div>
</div>
{%endif%}
{% endfor %}
<div style="border-left: solid 3px rgb(0, 0, 0); margin-left: 19px; width: 60%; background-color: rgb(255, 255, 255);">
    <table style="width: 100%;">
        <tr>
            <td>Order Value: </td>
            <td style="padding-left: 10px;"> </td>
            <td style="padding-left: 40px;"> </td>
            <td style="padding-left: 90px;"> </td>
            <td style="padding-left: 90px;">${{total}}</td>
        </tr>
        <tr>
            <td>Shipping: </td>
            <td style="padding-left: 10px;"> </td>
            <td style="padding-left: 40px;"> </td>
            <td style="padding-left: 90px;"> </td>
            <td style="padding-left: 90px;">$0</td>
        </tr>
        <tr>
            <td>Tax: </td>
            <td style="padding-left: 10px;"> </td>
            <td style="padding-left: 40px;"> </td>
            <td style="padding-left: 90px;"> </td>
            <td style="padding-left: 90px;">$0</td>
        </tr>
    </table>
    <hr>
    <table style="width: 100%;">
        <tr>
            <td>Total: </td>
            <td style="padding-left: 10px;"> </td>
            <td style="padding-left: 40px;"> </td>
            <td style="padding-left: 90px;"> </td>
            <td style="padding-left: 140px;">${{total}}</td>
        </tr>
    </table>

    <div style="margin-left: auto; margin-right: auto;">
    <form action="{% url 'purchaseSuccess' %}" method="POST" >
        {%csrf_token%}
        <input type="text" name="purchasedItemIds" value="{{cartIds}}" required="" id="id_purchasedItemIds" style="display: none;">
        <input type="text" name="purchaseOwner" value="{{request.user.id}}" required="" id="id_cartOwner" style="display: none;">
        <input type="text" name="size" value="{{cartSize}}" required="" id="id_size" style="display: none;">
        <input type="text" name="totalPrice" value="{{total}}"  required="" id="id_totalPrice" style="display: none;">
        <input class="btn btn--sub" type="submit" value="Purchase" >
      </form>
      </div>
</div>
{%endif%}
{%endblock content%}

Downloads/TCCclothing-main/projects/templates/profiles.html
{% extends 'projects/main.html' %}

{% block content %}
<h1>Usr</h1>
{% endblock %}

Downloads/TCCclothing-main/projects/templates/single-project.html
{% extends 'projects/main.html' %}

{% block content %}
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Available Colors</h3>
          <div class="singleProject__toolStack">
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{i.color.color_name}}</small>
            </span>
         
          </div>
            {% if project.source_link%}
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Source Code
          </a>
            {% endif %}
            {% if project.demo_link%}
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Live Demo
          </a>
            {% endif %}
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{i.picture.url}}" alt="portfolio thumbnail" style="margin-left: 10%; width: 60%; height: 50%;"/>
          <div class="comments" style="margin-top: -.5%;"></div>
          <a href="profile.html" class="singleProject__developer">{{i.details.gender}}</a>
          <h2 class="singleProject__title" style="display: inline; margin-right: 13%;">{{i.item_name}}</h2>
          <form action="{% url 'addToCartView' i.id %}" method="POST">
            {%csrf_token%}
            <select name="size" id="id_size" style="border-width: .5px; width:120px; height:45px; background-color: rgb(255, 255, 255); border-radius: 7px;" required oninvalid="this.setCustomValidity('Please choose a size')"
            oninput="this.setCustomValidity('')">
              <option value="" disabled selected hidden>Choose size</option>
              <!-- Selection based on clothing type and gender -->
              <!-- Selection based on clothing type and gender -->
              {%if i.type == "Bottoms" and i.gender == "Women" %}
              <option value="6">6</option>
              <option value="8">8</option>
              <option value="10">10</option>
              <option value="12">12</option>
              <option value="14">14</option>
              <option value="16">16</option>
              {% endif %}
              {%if i.type == "Bottoms" and i.gender == "Men" %}
              <option value="28">28</option>
              <option value="29">29</option>
              <option value="30">30</option>
              <option value="31">31</option>
              <option value="32">32</option>
              <option value="33">33</option>
              <option value="34">34</option>
              {% endif %}
              {%if i.type == "Tops" or i.gender == "Kids" %}
              <option value="XS">XS</option>
              <option value="S">S</option>
              <option value="M">M</option>
              <option value="L">L</option>
              <option value="XL">XL</option>
              {% endif %}
            </select>
            <input type="text" name="itemInCart" value="{{i.id}}" min="0" required="" id="id_itemInCart" style="display: none;">
            <input type="text" name="cartOwner" value="{{request.user.id}}" required="" id="id_cartOwner" style="display: none;">
            <input type="number" name="quantity" value="1" min="0" required="" id="id_quantity" style="display: none;">
            <input class="btn btn--sub" type="submit" value="Add to cart">
          </form>
          <br>
          <br>
          <h3 class="singleProject__subtitle">About the Product</h3>
          <div class="singleProject__info">
           {{i.details}}
          </div>
          <div class="comments">
            <h3 class="singleProject__subtitle">Leave a Review</h3>
            <form class="form" action="{% url 'project' i.id %}" method="POST">
              {%csrf_token%}
              
              {%for field in form%}
              <!-- Textarea -->
              <div class="form__field">
                <label for="id_body">Comments: </label>
                <textarea class="input input--textarea" name="body" id="id_body"
                  placeholder="Write your review here..." value=""></textarea>
              </div>
              <input class="btn btn--sub btn--lg" type="submit" value="Comment" />
              {%endfor%}
            </form><br><br>
            <h3 class="singleProject__subtitle">Reviews:</h3>
            <div class="commentList">
              {%for rev in review%}
              {%if rev.item.id == i.id %}
              <div class="comment" style="display: block; margin-bottom: 15px;">
                <div style="display: inline; margin-bottom: 15px;">
                <p style="display: inline;"><span style="color: rgb(0, 159, 250);">{{rev.owner}}</span> says:</p>
                </div>
                <div class="comment__details"  style="display: inline; margin-bottom: 15px;">
                  <a href="profile.html" class="comment__author"></a>
                    <p>{{rev.body}}</p>
                  </p>
                  <br>  
                </div>
                {% endif %}
                {%endfor%}
                {% if revLen == 0 %}
                <div class="comment" style="display: block; margin-bottom: 15px;">
                  <div style="display: inline; margin-bottom: 15px;">
                  </div>
                  <div class="comment__details"  style="display: inline; margin-bottom: 15px;">
                      <p>No reviews yet!</p>
                    <br>  
                  </div>
                {% endif %}
              </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>
<br>
<p></p>
{% endblock  %}